# ===============================
# Application
# ===============================
spring.application.name=browser-auth-jwt
server.port=8083

# ===============================
# Database (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/browser_auth_jwt
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=none  
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# Liquibase
# ===============================
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.contexts=dev
spring.liquibase.default-schema=browser_auth_jwt
spring.liquibase.drop-first=false

# ===============================
# Spring Security
# ===============================
spring.security.user.name=disabled
spring.security.user.password=disabled

# ===============================
# JWT (Custom)
# ===============================
jwt.secret=k3F4Q2pX8M7N5ZcY9R1Vb6T0sLwAEdJmSxHqUoKCIeP=
